#ifndef COLLECTORSPEEDSANDPOSITIONS_H
#define COLLECTORSPEEDSANDPOSITIONS_H

#define COLLECTOR_WHEELS_SPINNING_UP_CLOCKWISE //Is this necessary?

#define COLLECTOR_WHEELS_SPINNING_UP_COUNTERCLOCKWISE //Same question here

#define COLLECTOR_WHEELS_SPINNING_DOWN

#define TARGET_LOAD_SPEED (-0.5)

#define TARGET_EJECT_SPEED (0.5)

#endif //COLLECTORSPEEDSANDPOSITIONS_H
