// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Robot.h"
#include "Commands/SingleBallAutonomousCommand.h"
#include "Commands/TwoBallAutonomousCommand.h"
#include "Commands/ThreeBallAutonomousCommand.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
DriveSubsystem* Robot::driveSubsystem = 0;
ShooterArm* Robot::shooterArm = 0;
ShooterWheels* Robot::shooterWheels = 0;
Collector* Robot::collector = 0;
Camera* Robot::camera = 0;
Shifters* Robot::shifters = 0;
ShooterPiston* Robot::shooterPiston = 0;
CompressorSubsystem* Robot::compressorSubsystem = 0;
OI* Robot::oi = 0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
void Robot::RobotInit()
{
    RobotMap::init();
//    Robot::theRobot = this;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveSubsystem = new DriveSubsystem();
	shooterArm = new ShooterArm();
	shooterWheels = new ShooterWheels();
	collector = new Collector();
	camera = new Camera();
	shifters = new Shifters();
	shooterPiston = new ShooterPiston();
	compressorSubsystem = new CompressorSubsystem();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    // This MUST be here. If the OI creates Commands (which it very likely
    // will), constructing it during the construction of CommandBase (from
    // which commands extend), subsystems are not guaranteed to be
    // yet. Thus, their requires() statements may grab null pointers. Bad
    // news. Don't move it.
    oi = new OI();
    lw = LiveWindow::GetInstance();
    // instantiate the command used for the autonomous period
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	autonomousCommand = new AutonomousCommand();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    autoChooser = new SendableChooser();
    autoChooser->AddDefault("Single Ball Auton", new SingleBallAutonomousCommand());
    autoChooser->AddObject("Two Ball Auton", new TwoBallAutonomousCommand());
    autoChooser->AddObject("Three Ball Auton", new ThreeBallAutonomousCommand());
    SmartDashboard::PutData("Autonomous Mode:", autoChooser);
    
    SmartDashboard::PutNumber("Goal Distance", 0.0);
    SmartDashboard::PutString("Goal Side", "Taco Bell");
}
void Robot::AutonomousInit()
{
    driveSubsystem->theDriveTrain->SetSafetyEnabled(false);
    autonomousCommand = (Command *) autoChooser->GetSelected();
    if (autonomousCommand != NULL)
        autonomousCommand->Start();
}
void Robot::AutonomousPeriodic()
{
    oi->UpdateShotType();
    Scheduler::GetInstance()->Run();
}
void Robot::TeleopInit()
{
    driveSubsystem->theDriveTrain->SetSafetyEnabled(true);
    driveSubsystem->theDriveTrain->SetExpiration(0.5);
    // This makes sure that the autonomous stops running when
    // teleop starts running. If you want the autonomous to 
    // continue until interrupted by another command, remove
    // this line or comment it out.
    autonomousCommand->Cancel();
    shooterWheels->SetPower(0.0);
}
void Robot::TeleopPeriodic()
{
    oi->UpdateShotType();
    Scheduler::GetInstance()->Run();
    float leftRPM, rightRPM;
    shooterWheels->GetRpm(rightRPM,leftRPM);
    SmartDashboard::PutNumber("Left RPM",leftRPM);
    SmartDashboard::PutNumber("Right RPM",rightRPM);
    SmartDashboard::PutNumber("Arm Angle", shooterArm->GetCurrentAngle());
}
void Robot::TestPeriodic()
{
    lw->Run();
    float leftRPM, rightRPM;
    shooterWheels->GetRpm(rightRPM,leftRPM);
    SmartDashboard::PutNumber("Left RPM",leftRPM);
    SmartDashboard::PutNumber("Right RPM",rightRPM);
    SmartDashboard::PutNumber("Arm Angle", shooterArm->GetCurrentAngle());
    
//    static Timer imageTimer;
//    
//    if (imageTimer.Get() == 0.0)
//        imageTimer.Start();
//    
//    if (imageTimer.HasPeriodPassed(1.0))
//    {
//        imageTimer.Reset();
//        SmartDashboard::PutNumber("Goal Distance", camera->DetectDistance());
//        string side = "";
//        switch(camera->DetectHotGoal())
//        {
//            case Camera::notDetected:
//                side = "Not Detected";
//                break;
//            case Camera::goalLeft:
//                side = "Left";
//                break;
//            case Camera::goalRight:
//                side = "Right";
//                break;
//            case Camera::neverLooked:
//                side = "Can't Be Bothered";
//                break;
//        }
//        SmartDashboard::PutString("Goal Side", side);
//    }
}
void Robot::DisabledInit()
{
    shooterArm->Disable();
}
void Robot::DisabledPeriodic()
{
    float leftRPM, rightRPM;
    
    shooterWheels->GetRpm(rightRPM,leftRPM);
    SmartDashboard::PutNumber("Left RPM",leftRPM);
    SmartDashboard::PutNumber("Right RPM",rightRPM);
    SmartDashboard::PutNumber("Arm Angle", shooterArm->GetCurrentAngle());
    
    static bool camPushed = false;
    Joystick *op = oi->getoperatorStick();
    if (op->GetRawButton(1) && (camPushed == false))
    {
        camera->SaveImages("hsl_test",false);
    }
    else
    {
        camPushed = false;
    }
    
    
//    static Timer imageTimer;
//    
//    if (imageTimer.Get() == 0.0)
//        imageTimer.Start();
//    
//    if (imageTimer.HasPeriodPassed(1.0))
//    {
//        imageTimer.Reset();
//        //SmartDashboard::PutNumber("Goal Distance", camera->DetectDistance());
//        string side = "";
//        switch(camera->DetectHotGoal())
//        {
//            case Camera::notDetected:
//                side = "Not Detected";
//                break;
//            case Camera::goalLeft:
//                side = "Left";
//                break;
//            case Camera::goalRight:
//                side = "Right";
//                break;
//            case Camera::neverLooked:
//                side = "Can't Be Bothered";
//                break;
//        }
//        SmartDashboard::PutString("Goal Side", side);
//    }
}
START_ROBOT_CLASS(Robot)
;
