// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static SpeedController* driveSubsystemleftDrive;
	static SpeedController* driveSubsystemrightDrive;
	static RobotDrive* driveSubsystemTheDriveTrain;
	static Encoder* driveSubsystemleftEncoder;
	static Encoder* driveSubsystemrightEncoder;
	static Gyro* driveSubsystemdriveGyro;
	static AnalogChannel* shooterArmshooterArmPot;
	static SpeedController* shooterArmshooterArmMotor;
	static SpeedController* shooterWheelsrightWheelMotor;
	static SpeedController* shooterWheelsleftWheelMotor;
	static DoubleSolenoid* collectorcollectorLifter;
	static SpeedController* collectorrollerMotor;
	static SpeedController* blockerblockerWinch;
	static DigitalInput* blockerraisedLimitSwitch;
	static DoubleSolenoid* shiftersshiftSolenoid;
	static DoubleSolenoid* shooterPistonFiringSolenoid;
	static Compressor* compressorSubsystemTheCompressor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static void init();
};
#endif
