// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveSubsystemleftDrive = NULL;
SpeedController* RobotMap::driveSubsystemrightDrive = NULL;
RobotDrive* RobotMap::driveSubsystemTheDriveTrain = NULL;
Encoder* RobotMap::driveSubsystemleftEncoder = NULL;
Encoder* RobotMap::driveSubsystemrightEncoder = NULL;
Gyro* RobotMap::driveSubsystemdriveGyro = NULL;
Accelerometer* RobotMap::driveSubsystemdriveAccelerometer = NULL;
AnalogChannel* RobotMap::shooterArmshooterArmPot = NULL;
SpeedController* RobotMap::shooterArmshooterArmMotor = NULL;
SpeedController* RobotMap::shooterWheelsrightWheelMotor = NULL;
SpeedController* RobotMap::shooterWheelsleftWheelMotor = NULL;
DoubleSolenoid* RobotMap::shooterWheelsFiringSolenoid = NULL;
DoubleSolenoid* RobotMap::collectorcollectorLifter = NULL;
SpeedController* RobotMap::collectorrollerMotor = NULL;
SpeedController* RobotMap::blockerblockerWinch = NULL;
DigitalInput* RobotMap::blockerraisedLimitSwitch = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	driveSubsystemleftDrive = new Talon(1, 1);
	lw->AddActuator("DriveSubsystem", "leftDrive", (Talon*) driveSubsystemleftDrive);
	
	driveSubsystemrightDrive = new Talon(1, 2);
	lw->AddActuator("DriveSubsystem", "rightDrive", (Talon*) driveSubsystemrightDrive);
	
	driveSubsystemTheDriveTrain = new RobotDrive(driveSubsystemleftDrive, driveSubsystemrightDrive);
	
	driveSubsystemTheDriveTrain->SetSafetyEnabled(true);
        driveSubsystemTheDriveTrain->SetExpiration(0.1);
        driveSubsystemTheDriveTrain->SetSensitivity(0.5);
        driveSubsystemTheDriveTrain->SetMaxOutput(1.0);
        driveSubsystemTheDriveTrain->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);        
	driveSubsystemleftEncoder = new Encoder(1, 1, 1, 2, false, Encoder::k4X);
	lw->AddSensor("DriveSubsystem", "leftEncoder", driveSubsystemleftEncoder);
	driveSubsystemleftEncoder->SetDistancePerPulse(1.0);
        driveSubsystemleftEncoder->SetPIDSourceParameter(Encoder::kRate);
        driveSubsystemleftEncoder->Start();
	driveSubsystemrightEncoder = new Encoder(1, 3, 1, 4, false, Encoder::k4X);
	lw->AddSensor("DriveSubsystem", "rightEncoder", driveSubsystemrightEncoder);
	driveSubsystemrightEncoder->SetDistancePerPulse(1.0);
        driveSubsystemrightEncoder->SetPIDSourceParameter(Encoder::kRate);
        driveSubsystemrightEncoder->Start();
	driveSubsystemdriveGyro = new Gyro(1, 1);
	lw->AddSensor("DriveSubsystem", "driveGyro", driveSubsystemdriveGyro);
	driveSubsystemdriveGyro->SetSensitivity(0.007);
	driveSubsystemdriveAccelerometer = new Accelerometer(1, 2);
	lw->AddSensor("DriveSubsystem", "driveAccelerometer", driveSubsystemdriveAccelerometer);
	driveSubsystemdriveAccelerometer->SetSensitivity(1.0);
        driveSubsystemdriveAccelerometer->SetZero(2.5);
	shooterArmshooterArmPot = new AnalogChannel(1, 3);
	lw->AddSensor("ShooterArm", "shooterArmPot", shooterArmshooterArmPot);
	
	shooterArmshooterArmMotor = new Talon(1, 5);
	lw->AddActuator("ShooterArm", "shooterArmMotor", (Talon*) shooterArmshooterArmMotor);
	
	shooterWheelsrightWheelMotor = new Talon(1, 6);
	lw->AddActuator("ShooterWheels", "rightWheelMotor", (Talon*) shooterWheelsrightWheelMotor);
	
	shooterWheelsleftWheelMotor = new Talon(1, 7);
	lw->AddActuator("ShooterWheels", "leftWheelMotor", (Talon*) shooterWheelsleftWheelMotor);
	
	shooterWheelsFiringSolenoid = new DoubleSolenoid(1, 7, 8);      
	
	
	collectorcollectorLifter = new DoubleSolenoid(1, 1, 2);      
	
	
	collectorrollerMotor = new Talon(1, 8);
	lw->AddActuator("Collector", "rollerMotor", (Talon*) collectorrollerMotor);
	
	blockerblockerWinch = new Talon(1, 9);
	lw->AddActuator("Blocker", "blockerWinch", (Talon*) blockerblockerWinch);
	
	blockerraisedLimitSwitch = new DigitalInput(1, 9);
	lw->AddSensor("Blocker", "raisedLimitSwitch", blockerraisedLimitSwitch);
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
