#ifndef SHOOTERARMPOSITIONS_H
#define SHOOTERARMPOSITIONS_H

#define SHOOTER_ARM_TARGET_EJECT_POSITION 0.0


#define SHOOTER_ARM_TARGET_LOAD_POSITION -15.0


#define SHOOTER_ARM_TARGET_TRUSS 80.0


#define SHOOTER_IDLE 0.0

#define ARM_TARGET_AUTONOMOUS_1 75.0

#define ARM_TARGET_AUTONOMOUS_2 75.0

#define ARM_TARGET_AUTONOMOUS_3 75.0

#define SHOOTER_ARM_TUNING_MODE 0.0

#define ARM_TARGET_LONG_GOAL 50.0


#define ARM_TARGET_SHORT_GOAL 75.0

#define SHOOTER_ARM_AUTO_TARGET 75.0

#define SHOOTER_ARM_TARGET 75.0

#define SHOOTER_ARM_DISMOUNT 70.0

#endif //SHOOTERARMPOSITIONS_H
