#ifndef SHOOTERWHEELS_SPEEDS_H
#define SHOOTERWHEELS_SPEEDS_H


#define TARGET_LONG_GOAL_SPEED (4300)
#define TARGET_AUTONOMOUS_1_SPEED (4300)
#define TARGET_AUTONOMOUS_2_SPEED (4300)
#define TARGET_AUTONOMOUS_3_SPEED (4300)

#define TARGET_SHORT_GOAL_SPEED (3200)
#define TARGET_TRUSS_SPEED (3200)

#define TARGET_EJECT_POWER (-0.4)
#define TARGET_LOAD_POWER (0.4)



#define SPEED_TOLERANCE (0.05)
#define BALL_ESCAPE_TIME (0.5)
#define MAX_RPM (5000)
#define MAX_BIAS (0.2)
#define TAKE_BACK_TIME (0.4)
#define TAKE_BACK_POWER (0.8)
#define AUTONOMOUS_BIAS (0.1)

#endif //SHOOTERWHEELS_SPEEDS_H
