#ifndef SHOOTERWHEELS_SPEEDS_H
#define SHOOTERWHEELS_SPEEDS_H

#define	WHEELS_SPINNING_UP

#define WHEELS_SPINNING_DOWN

#define UPPER_RPM_LIMIT(rpm) (rpm + (rpm*0.1))

#define LOWER_RPM_LIMIT(rpm) (rpm - (rpm*0.1))

#define MAX_RPM (5000)

#define TARGET_EJECT_SPEED

#define TARGET_TRUSS_SPEED

#define TARGET_LOAD_SPEED

#define TARGET_AUTO_SPEED

#endif //SHOOTERWHEELS_SPEEDS_H
