#ifndef SHOOTERARMPOSITIONS_H
#define SHOOTERARMPOSITIONS_H

#define SHOOTER_ARM_TARGET_EJECT_POSITION 0.0

#define SHOOTER_ARM_TARGET_LOAD_POSITION 0.0

#define SHOOTER_ARM_TARGET_TRUSS 80.0

#define SHOOTER_ARM_TARGET_CATCH 100.0


#define ARM_TARGET_LONG_GOAL 40.0

#define ARM_TARGET_AUTONOMOUS_1 ARM_TARGET_LONG_GOAL

#define ARM_TARGET_AUTONOMOUS_2 ARM_TARGET_LONG_GOAL

#define ARM_TARGET_AUTONOMOUS_3 ARM_TARGET_LONG_GOAL


#define ARM_TARGET_SHORT_GOAL 50.0

#define SHOOTER_ARM_DISMOUNT 85.0

#define ARM_START_POSITION 64.0

#endif //SHOOTERARMPOSITIONS_H
