#ifndef SHOOTERARMPOSITIONS_H
#define SHOOTERARMPOSITIONS_H

#define SHOOTER_ARM_TARGET_EJECT_POSITION 10.0

#define SHOOTER_ARM_TARGET_LOAD_POSITION 10.0

#define SHOOTER_ARM_TARGET_TRUSS 80.0

#define ARM_TARGET_AUTONOMOUS_1 60.0

#define ARM_TARGET_AUTONOMOUS_2 61.0

#define ARM_TARGET_AUTONOMOUS_3 62.0

#define ARM_TARGET_LONG_GOAL 50.0

#define ARM_TARGET_SHORT_GOAL 40.0

#define SHOOTER_ARM_DISMOUNT 85.0

#endif //SHOOTERARMPOSITIONS_H
