// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#include "BackwardAuto.h"
#include "ManualFlipperDown.h"
#include "CollectorDown.h"
#include "ShooterSetRpm.h"
#include "../ShooterWheelsSpeeds.h"
#include "Shoot.h" 
#include "DriveTwoSeconds.h"
#include "ArmTargetAngle.h"
#include "Collect.h"
#include "../ShooterArmPositions.h"
#include "CollectUntilTrigger.h"
#include "ArmTargetPosition.h"


BackwardAuto::BackwardAuto() {
	
	AddParallel(new ManualFlipperDown());
	AddParallel(new ArmTargetAngle(ARM_TARGET_BACKWARDS_AUTONOMOUS));
	AddSequential(new Collect(), 0.5);
	
	AddParallel(new CollectUntilTrigger(), 1.5);
	AddParallel(new ShooterSetRpm(2100));
	AddSequential(new DriveTwoSeconds(2.5, -0.5));
	
	AddSequential(new Shoot());
	AddParallel(new ShooterSetRpm(0.0));
	AddSequential(new TargetLoadPosition());
	
	AddParallel(new ShooterSetRpm(2100));
	AddSequential(new ArmTargetAngle(ARM_TARGET_BACKWARDS_AUTONOMOUS));
	
	AddSequential(new Shoot());
	AddSequential(new ShooterSetRpm(0.0));
	
	
	
	
	
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.

	// To run multiple commands at the same time,
	// use AddParallel()
	// e.g. AddParallel(new Command1());
	//      AddSequential(new Command2());
	// Command1 and Command2 will run in parallel.

	// A command group will require all of the subsystems that each member
	// would require.
	// e.g. if Command1 requires chassis, and Command2 requires arm,
	// a CommandGroup containing them would require both the chassis and the
	// arm.
}
