// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "BlockerRaise.h"
BlockerRaise::BlockerRaise() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::blocker);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void BlockerRaise::Initialize() {
	Robot::blocker->blockerWinch->Set(.6);
}
// Called repeatedly when this Command is scheduled to run
void BlockerRaise::Execute() {
	if(Robot::blocker->raisedLimitSwitch->Get() != 1.0)
	{
		Robot::blocker->blockerWinch->Set(.6);
	}
	else
	{
		Robot::blocker->blockerWinch->Set(0.0);
	}
}
// Make this return true when this Command no longer needs to run execute()
bool BlockerRaise::IsFinished() {
	return Robot::blocker->raisedLimitSwitch->Get() == 0.0;
}
// Called once after isFinished returns true
void BlockerRaise::End() {
	Robot::blocker->blockerWinch->Set(0.0);
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void BlockerRaise::Interrupted() {
}
