// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Collect.h"
#include "../Subsystems/Collector.h"
Collect::Collect(float power):CollectorLoad(power) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::collector);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Collect::Initialize() {
    Collector *col = Robot::collector;
    CollectorLoad::Initialize();
    col->SetCollectorPosition(true);
}
// Called repeatedly when this Command is scheduled to run
void Collect::Execute() {
    Collector *col = Robot::collector;
    col->SetAutoFlipTimeout(2.5);
    if (col->GetState() == Collector::DOWN)
    {
        col->SetFlipperPosition(true);
    }
    if (col->GetFlipperState() == Collector::F_DOWN)
    {
        CollectorLoad::Execute();
    }
}
// Make this return true when this Command no longer needs to run execute()
bool Collect::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void Collect::End() {
	Robot::collector->Idle();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Collect::Interrupted() {
	End();
}
