// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "DetectHotGoal.h"
#include "../Subsystems/Camera.h"
DetectHotGoal::DetectHotGoal() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::camera);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	_done = false;
	SetTimeout(1.5);
}
// Called just before this Command runs the first time
void DetectHotGoal::Initialize() {
}
// Called repeatedly when this Command is scheduled to run
void DetectHotGoal::Execute() {
	Camera *camera = Robot::camera;
	if (_done = false)
	{
	    if (camera->GetHotGoal() != Camera::neverLooked)
	        _done = true;
	    
	}
	
    string side = "";
    switch(camera->DetectHotGoal())
    {
        case Camera::notDetected:
            side = "Not Detected";
            break;
        case Camera::goalLeft:
            side = "Left";
            break;
        case Camera::goalRight:
            side = "Right";
            break;
        case Camera::neverLooked:
            side = "Can't Be Bothered";
            break;
    }
    SmartDashboard::PutString("Goal Side", side);
	
}
// Make this return true when this Command no longer needs to run execute()
bool DetectHotGoal::IsFinished() {
	return _done;
}
// Called once after isFinished returns true
void DetectHotGoal::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DetectHotGoal::Interrupted() {
}
