// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "DriveTwoSeconds.h"
#include "../Subsystems/DriveSubsystem.h"

DriveTwoSeconds::DriveTwoSeconds() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveSubsystem);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	_isFinished = false;
}

// Called just before this Command runs the first time
void DriveTwoSeconds::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void DriveTwoSeconds::Execute() {
	{
	if (_isFinished = false)
		{
			Robot::driveSubsystem->FunWithTimers();
			_isFinished = true;
		}
	}
	
}

// Make this return true when this Command no longer needs to run execute()
bool DriveTwoSeconds::IsFinished() {
	return _isFinished;
}

// Called once after isFinished returns true
void DriveTwoSeconds::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void DriveTwoSeconds::Interrupted() {

}
