// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ShooterArmTuningMode.h"
#include "../ShooterArmPositions.h"
ShooterArmTuningMode::ShooterArmTuningMode() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterArm);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    ShooterArm *arm = Robot::shooterArm;
	_p = arm->GetThePIDController()->GetP();
	_i2 = arm->GetThePIDController()->GetI();
	_d2 = arm->GetThePIDController()->GetD();
	_i1 = 0.0;
	_d1 = 0.0;
	_tol1 = 10.0;
	_tol2 = 3.0;
	
	//_f = arm->GetThePIDController()->GetF();
}
// Called just before this Command runs the first time
void ShooterArmTuningMode::Initialize() {
    _angle = Robot::shooterArm->GetCurrentAngle();
    _enabled = false;
    SmartDashboard::PutNumber("Angle",_angle);
    SmartDashboard::PutBoolean("Enable", _enabled);
    SmartDashboard::PutNumber("P",_p);
    SmartDashboard::PutNumber("D1",_d1);
    SmartDashboard::PutNumber("I1",_i1);
    SmartDashboard::PutNumber("D2",_d2);
    SmartDashboard::PutNumber("I2",_i2);
    SmartDashboard::PutNumber("Tol1",_tol1);
    SmartDashboard::PutNumber("Tol2",_tol2);
}
// Called repeatedly when this Command is scheduled to run
void ShooterArmTuningMode::Execute() {
    ShooterArm *arm = Robot::shooterArm;
    SmartDashboard::PutNumber("CurrentAngle", arm->GetCurrentAngle());
    SmartDashboard::PutNumber("CurrentVolts", arm->shooterArmPot->GetVoltage());
    SmartDashboard::PutNumber("Command", arm->shooterArmMotor->Get());
    SmartDashboard::PutNumber("SetP", arm->GetThePIDController()->GetP());
    SmartDashboard::PutNumber("SetI", arm->GetThePIDController()->GetI());
    SmartDashboard::PutNumber("SetD", arm->GetThePIDController()->GetD());
    SmartDashboard::PutNumber("SetTarget", arm->GetThePIDController()->GetSetpoint());
    SmartDashboard::PutBoolean("Stage1 Complete", arm->IsStage2());
    SmartDashboard::PutBoolean("Stage2 Complete", arm->IsOnTarget());
    
    _angle = SmartDashboard::GetNumber("Angle");
    _p = SmartDashboard::GetNumber("P");
    _d1 = SmartDashboard::GetNumber("D1");
    _d2 = SmartDashboard::GetNumber("D2");
    _i1 = SmartDashboard::GetNumber("I1");
    _i2 = SmartDashboard::GetNumber("I2");
    _tol1 = SmartDashboard::GetNumber("Tol1");
    _tol2 = SmartDashboard::GetNumber("Tol2");
    //_f = SmartDashboard::GetNumber("F");
    _enabled = SmartDashboard::GetBoolean("Enable");
    static bool prevEnabled = false; 
	if ((_enabled == true) && (prevEnabled == false))
	{
	    arm->TestPID(_angle, _p, _i1, _i2, _d1,_d2, _tol1, _tol2);
	    prevEnabled = true;
	}
	else if (_enabled == false)
	{
	    arm->Disable();
	    prevEnabled = false;
	}
	
	
	
//	arm->SetTargetAngle(SHOOTER_ARM_TUNING_MODE);
}
// Make this return true when this Command no longer needs to run execute()
bool ShooterArmTuningMode::IsFinished() {
    return false;
			
}
// Called once after isFinished returns true
void ShooterArmTuningMode::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterArmTuningMode::Interrupted() {
    Robot::shooterArm->Disable();
}
