// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ShooterSetRpm.h"
ShooterSetRpm::ShooterSetRpm(float rpm, bool absoluteTolerance, float tolerance, float takeBackPower) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterWheels);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	_setpoint = rpm;
	_absoluteTolerance = absoluteTolerance;
	_tolerance = tolerance;
}
// Called just before this Command runs the first time
void ShooterSetRpm::Initialize() {
    Robot::shooterWheels->SetTargetRpm(_setpoint, _absoluteTolerance, _tolerance);   
}
// Called repeatedly when this Command is scheduled to run
void ShooterSetRpm::Execute() {
	
}
// Make this return true when this Command no longer needs to run execute()
bool ShooterSetRpm::IsFinished() {
	return true;
}
// Called once after isFinished returns true
void ShooterSetRpm::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ShooterSetRpm::Interrupted() {
}
