// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#include "ThreeBallAutonomousCommand.h"

ThreeBallAutonomousCommand::ThreeBallAutonomousCommand() {
	AddSequential(new CollectorDown());
	AddParallel(new ArmTargetAutonomous1());
	AddSequential(new WheelTargetAutonomous1());
	AddSequential(new Shoot());
	AddSequential(new CollectorLoad());
	AddSequential(new ShooterArmTargetLoadPosition());
	AddParallel(new ArmTargetAutonomous2());
	AddParallel(new CollectorIdle());
	AddSequential(new WheelTargetAutonomous2());
	AddSequential(new Shoot());
	AddSequential(new DriveTwoFeet());
	AddSequential(new DriveTwoFeet());
}
