// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Turn90Degrees.h"
#include "../Subsystems/DriveSubsystem.h"

Turn90Degrees::Turn90Degrees() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveSubsystem);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Turn90Degrees::Initialize() {
	_isFinished = false;
}
// Called repeatedly when this Command is scheduled to run
void Turn90Degrees::Execute() {
	DriveSubsystem *turn = Robot::driveSubsystem;
		if (_isFinished == false)
		{
			_isFinished = turn->TurnToAngle(90);
		}
}
// Make this return true when this Command no longer needs to run execute()
bool Turn90Degrees::IsFinished() {
	
	return _isFinished;
}
// Called once after isFinished returns true
void Turn90Degrees::End() {
	DriveSubsystem *turn = Robot::driveSubsystem;
	turn->Cancel();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Turn90Degrees::Interrupted() {
	DriveSubsystem *turn = Robot::driveSubsystem;
	turn->Cancel();
}
