// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef COLLECTOR_H
#define COLLECTOR_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#define TIME_TRAVELING_UP 1.0
#define TIME_TRAVELING_DOWN 1.0
/**
 *
 *
 * @author ExampleAuthor
 */
class Collector: public Subsystem {
private:
	//Timer travelUpTime;
	//Timer travelDownTime;
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DoubleSolenoid* collectorLifter;
	SpeedController* rollerMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Collector();
	void InitDefaultCommand();
	void MoveCollector(bool extend);
	void Pickup();
	void Spit();
	void Idle();
	typedef enum {IDLE,UP,DOWN,TRAVELING_UP,TRAVELING_DOWN}CollectorState;
	CollectorState GetState();
};
#endif
